version: 2
jobs:
  build:
    docker:
      - image: python:3.6
        environment:
          CONDA_ENV_FILE: .cricleci/py36_conda_env.yaml
    working_directory: ~/agdc_statistics
    steps:
      - run:
          name: Install Conda + Setup Conda
          working_directory: ~
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -f -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda config --show-sources
            conda config --show
            conda config --prepend channels conda-forge
            conda update --all
            conda info -a

      - checkout

      - run:
          name: Setup Environment
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            conda env create -q -n agdc --file $CONDA_ENV_FILE
            source activate agdc


      - run:
          name: Install App
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate agdc
            pip install . --no-deps --upgrade

      - run:
          name: Run All Tests
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate agdc

            pep8 tests integration_tests examples utils --max-line-length 120

            pylint -j 2 --reports no datacube datacube_apps

            # Run tests, taking coverage.
            # Users can specify extra folders as arguments.
            py.test --junitxml=test-reports/pytest-datacube.log -r sx --cov datacube --durations=5 datacube tests datacube_apps integration_tests


      - store_artifacts:
          path: test-reports
          destination: reports

      - store_test_results:
          path: test-reports

