output_products:
    - name: mangrove_extent_cover_albers
      product_type: mangrove_extent_cover
      statistic: external
      metadata:
          format:
              name: NetCDF
          platform:
              code: LANDSAT_5,LANDSAT_7,LANDSAT_8
          instrument:
              name: TM,ETM+,OLI
      statistic_args:
          impl: datacube_stats.mangrove.MangroveCC
          thresholds: [15, 40, 62]
          shape_file: /g/data/v10/mangroves/GMW_UnionMangroveExtent_v1.3_Australia_epsg3577.shp
      file_path_template: 'MANGROVE_COVER/{x}_{y}/MANGROVE_COVER_3577_{x}_{y}_{epoch_start:%Y%m%d}.nc'
      output_params:
          zlib: True
          fletcher32: True

sources:
    - product: fc_percentile_albers_annual
      measurements: [PV_PC_10]
      crs: EPSG:3577

date_ranges:
    start_date: 2014-01-01
    end_date: 2015-01-01
    stats_duration: 1y
    step_size: 1y

location: /g/data/r78/mangrove_cover

storage:
    driver: NetCDF CF

    crs: EPSG:3577
    tile_size:
        x: 100000.0
        y: 100000.0
    resolution:
        x: 25
        y: -25
    chunking:
        x: 200
        y: 200
        time: 1
    dimension_order: [time, y, x]

global_attributes:
    title: Mangrove Canopy Cover - Annual
    product_version: Version 1.0.0, July 2018
    summary: 'The mangrove canopy cover product provides valuable information about
              the extent and canopy density of mangroves for each year between 1987
              and 2016 for the entire Australian coastline. The canopy cover classes
              are 20-50% (pale green), 50-80% (mid green), 80-100% (dark green). The
              product consists of a sequence (one per year) of 25 meter resolution
              maps that are generated by analysing the Landsat fractional cover
              (https://doi.org/10.6084/m9.figshare.94250.v1) developed by the Joint
              Remote Sensing Research Program and the Global Mangrove Watch layers
              (https://doi.org/10.1071/MF13177) developed by the Japanese Aerospace
              Exploration Agency.'

    institution: Commonwealth of Australia (Geoscience Australia)
    license: CC BY Attribution 4.0 International License
    keywords_vocabulary: GCMD
    keywords: AU/GA,NASA/GSFC/SED/ESD/LANDSAT,REFLECTANCEE,TM+,TM,OLI,EARTH SCIENCE
    platform: LANDSAT_5,LANDSAT_7,LANDSAT_8
    instrument: TM,ETM+,OLI
    publisher_type: institution
    publisher_email: earth.observation@ga.gov.au
    publisher_name: Section Leader, Operations Section, NEMO, Geoscience Australia
    publisher_url: http://www.ga.gov.au
    authurs: Leo Lymburner, Peter Bunting, Richard Lucas, Peter Scarth, Imam Alam, Claire Phillips, Catherine Ticehurst, Alex Held
    cdm_data_type: Grid
    source: Annual summary of Fractional Cover and WOfS
    acknowledgment: 'Landsat data is provided by the United States Geological Survey (USGS)
                     through direct reception of the data at Geoscience Australias satellite
                     reception facility or download. The fractional cover algorithm was developed
                     by the Joint Remote Sensing Research Program (JRSRP) and is described in
                     Scarth et al. (2010). While originally calibrated in Queensland, a large
                     collaborative effort between The Department of Agriculture & ABARES and
                     State and Territory governments to collect additional calibration data
                     has enabled the calibration to extend to the entire Australian continent.
                     FC_25 was made possible by new scientific and technical capabilities,
                     the collaborative framework established by the Terrestrial Ecosystem Research
                     Network (TERN) through the National Collaborative Research Infrastructure Strategy (NCRIS),
                     and collaborative effort between state and Commonwealth governments. This product
                     is the result of a collaboration between Geoscience Australia, the University of Aberyswyth,
                     CSIRO, the Joint Remote Sensing Research Program and the Terrestrial Ecosystem Research Network.
                     WOfS is being developed in parallel with the National Flood Studies Database system which wil
                     provide Flood Study documentation and reports to a wide range of users.
                     '
    references: 'Scarth, P., Roder, A. and Schmidt, M., 2010.
                 Tracking grazing pressure and climate interaction - the role of Landsat fractional cover in time series analysis,
                 Proceedings of the 15th Australasian Remote Sensing & Photogrammetry Conference, viewed 4 January 2011,
                 www.scribd.com/doc/37455672/15arspc-Submission-140.
                 Schmidt, M., Denham, R. and Scarth, P., 2010.
                 Fractional ground cover monitoring of pastures and agricultural areas in Queensland,
                 Proceedings of the 15th Australasian Remote Sensing & Photogrammetry Conference, viewed 4 January 2011,
                 www.scribd.com/doc/37455826/15arspc-Submission-119.
                 N. Mueller, A. Lewis, D. Roberts, S. Ring, R. Melrose, J. Sixsmith, L. Lymburner, A. McIntyre, P. Tan,
                 S. Curnow, A. Ip, Water observations from space: Mapping surface water from 25 years of Landsat imagery across Australia,
                 Remote Sensing of Environment, Volume 174, 1 March 2016, Pages 341-352, ISSN 0034-4257,
                 http://dx.doi.org/10.1016/j.rse.2015.11.003. (http://www.sciencedirect.com/science/article/pii/S0034425715301929).'

var_attributes:
    extent:
        long_name: Mangrove Canopy Cover Extent
        standard_name: mangrove_canopy_cover_extent
        coverage_content_type: qualityInformation
    canopy_cover_class:
        long_name: Mangrove Canopy Cover Class
        standard_name: mangrove_canopy_cover_class
        coverage_content_type: qualityInformation
